# Generated by Django 3.0 on 2023-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=1000)),
                ('nuit', models.CharField(max_length=1000)),
                ('endereco', models.CharField(max_length=1000)),
                ('vocacao', models.CharField(max_length=1000)),
                ('objectivo', models.CharField(max_length=1000)),
            ],
        ),
    ]
