# Generated by Django 3.0 on 2023-07-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_empresa_quitacao_historicalempresa_historicalempresa_quitacao_historicalpedidos_quitacao_historicalq'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedidos_quitacao',
            name='estado',
            field=models.CharField(default=23, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos_quitacao',
            name='estado',
            field=models.CharField(default='2', max_length=1000),
            preserve_default=False,
        ),
    ]
