# Generated by Django 3.0 on 2023-07-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0006_pagamnetos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicoes',
            fields=[
                ('idServico', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('valor', models.CharField(max_length=1000)),
            ],
        ),
    ]
