# Generated by Django 3.0 on 2023-07-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0008_auto_20230709_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(default='Maputo', max_length=1000),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provinvia',
            field=models.CharField(default='Maputo', max_length=1000),
        ),
        migrations.AddField(
            model_name='historicalempresa',
            name='cidade',
            field=models.CharField(default='Maputo', max_length=1000),
        ),
        migrations.AddField(
            model_name='historicalempresa',
            name='provinvia',
            field=models.CharField(default='Maputo', max_length=1000),
        ),
    ]
