# Generated by Django 3.0 on 2023-07-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0009_auto_20230710_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedidos_quitacao',
            name='estado_info_inter',
            field=models.CharField(default='processamento', max_length=1000),
        ),
        migrations.AddField(
            model_name='pedidos_quitacao',
            name='estado_info_inter',
            field=models.CharField(default='processamento', max_length=1000),
        ),
    ]
