# Generated by Django 3.0 on 2023-07-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0010_auto_20230710_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedidos_quitacao',
            name='revisto',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='pedidos_quitacao',
            name='revisto',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
