# Generated by Django 3.0 on 2023-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0012_auto_20230710_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquitacao',
            name='serialNumber',
            field=models.CharField(db_index=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quitacao',
            name='serialNumber',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
