# Generated by Django 3.0 on 2023-07-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0013_auto_20230710_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquitacao',
            name='idPedido',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapi.Pedidos_Quitacao'),
        ),
        migrations.AddField(
            model_name='quitacao',
            name='idPedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapi.Pedidos_Quitacao'),
        ),
    ]
