# Generated by Django 3.0 on 2023-08-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0014_auto_20230710_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedidos_quitacao',
            name='tipo_pedido',
            field=models.CharField(default='Atestado Medico', max_length=1000),
        ),
        migrations.AddField(
            model_name='pedidos_quitacao',
            name='tipo_pedido',
            field=models.CharField(default='Atestado Medico', max_length=1000),
        ),
    ]
