# Generated by Django 3.0 on 2023-08-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0015_auto_20230803_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpedidos_quitacao',
            name='tipo_pedido',
        ),
        migrations.RemoveField(
            model_name='pedidos_quitacao',
            name='tipo_pedido',
        ),
    ]
