# Generated by Django 3.0 on 2023-08-29 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0017_empresa_atencedentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa_atencedentes',
            name='data_submisao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
