# Generated by Django 3.0 on 2023-08-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0020_auto_20230830_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedidos_quitacao',
            name='assinalado_er',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='pedidos_quitacao',
            name='assinalado_er',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
