# Generated by Django 5.0.3 on 2024-03-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0021_auto_20230830_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalempresa',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical empresa', 'verbose_name_plural': 'historical empresas'},
        ),
        migrations.AlterModelOptions(
            name='historicalempresa_quitacao',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical empresa_ quitacao', 'verbose_name_plural': 'historical empresa_ quitacaos'},
        ),
        migrations.AlterModelOptions(
            name='historicalpedidos_quitacao',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical pedidos_ quitacao', 'verbose_name_plural': 'historical pedidos_ quitacaos'},
        ),
        migrations.AlterModelOptions(
            name='historicalquitacao',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical quitacao', 'verbose_name_plural': 'historical quitacaos'},
        ),
        migrations.AlterField(
            model_name='empresa_quitacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalempresa_quitacao',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalempresa_quitacao',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalpedidos_quitacao',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalquitacao',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
